=== antonelaabicic/GreatWesternTrail/xml/dtd/gameMoves.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT GameMoves (GameMove+)>
<!ELEMENT GameMove (PlayerState, TileState, Board, Time)>

<!ELEMENT PlayerState (Points, Money, TrainProgress, CowDeck, WorkerDeck)>
<!ELEMENT Points (#PCDATA)>
<!ELEMENT Money (#PCDATA)>
<!ELEMENT TrainProgress (#PCDATA)>
<!ELEMENT CowDeck (CowType+)>
<!ELEMENT CowType (CowQuantity)>
<!ATTLIST CowType name CDATA #REQUIRED>
<!ELEMENT CowQuantity (#PCDATA)>
<!ELEMENT WorkerDeck (WorkerType+)>
<!ELEMENT WorkerType (WorkerQuantity)>
<!ATTLIST WorkerType name CDATA #REQUIRED>
<!ELEMENT WorkerQuantity (#PCDATA)>

<!ELEMENT TileState (Position, TileType, BuildingType?, HazardType?, Objective?)>
<!ELEMENT Position (Row, Column)>
<!ELEMENT Row (#PCDATA)>
<!ELEMENT Column (#PCDATA)>
<!ELEMENT TileType (#PCDATA)>
<!ELEMENT BuildingType (#PCDATA)>
<!ELEMENT HazardType (#PCDATA)>
<!ELEMENT Objective (ObjectiveStatus, ObjectiveAction, ObjectiveQuantity)>
<!ELEMENT ObjectiveStatus (#PCDATA)>
<!ELEMENT ObjectiveAction (#PCDATA)>
<!ELEMENT ObjectiveQuantity (#PCDATA)>

<!ELEMENT Board (Tile+)>
<!ELEMENT Tile (Position, TileType, BuildingType?, HazardType?, Objective?)>

<!ELEMENT Time (#PCDATA)>

=== antonelaabicic/GreatWesternTrail/xml/gameMovesXML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GameMoves SYSTEM "dtd/gameMoves.dtd">
<GameMoves>
    <GameMove>
        <PlayerState>
            <Points>0</Points>
            <Money>75</Money>
            <TrainProgress>1.0</TrainProgress>
            <CowDeck>
                <CowType name="HOLSTEIN">
                    <CowQuantity>0</CowQuantity>
                </CowType>
                <CowType name="JERSEY">
                    <CowQuantity>1</CowQuantity>
                </CowType>
                <CowType name="BLACK_ANGUS">
                    <CowQuantity>2</CowQuantity>
                </CowType>
                <CowType name="TEXAS_LONGHORN">
                    <CowQuantity>1</CowQuantity>
                </CowType>
            </CowDeck>
            <WorkerDeck>
                <WorkerType name="COWBOY">
                    <WorkerQuantity>2</WorkerQuantity>
                </WorkerType>
                <WorkerType name="BUILDER">
                    <WorkerQuantity>1</WorkerQuantity>
                </WorkerType>
                <WorkerType name="ENGINEER">
                    <WorkerQuantity>1</WorkerQuantity>
                </WorkerType>
            </WorkerDeck>
        </PlayerState>
        <TileState>
            <Position>
                <Row>4</Row>
                <Column>3</Column>
            </Position>
            <TileType>EMPTY</TileType>
            <BuildingType>null</BuildingType>
            <HazardType>null</HazardType>
            <Objective>
                <ObjectiveStatus>HAS_OBJECTIVE</ObjectiveStatus>
                <ObjectiveAction>HIRE_BUILDER</ObjectiveAction>
                <ObjectiveQuantity>3</ObjectiveQuantity>
            </Objective>
        </TileState>
        <Board>
            <Tile>
                <Position>
                    <Row>0</Row>
                    <Column>0</Column>
                </Position>
                <TileType>END</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>0</Row>
                    <Column>1</Column>
                </Position>
                <TileType>BUILDING</TileType>
                <BuildingType>CATTLE_EXCHANGE</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>0</Row>
                    <Column>2</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>0</Row>
                    <Column>3</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>0</Row>
                    <Column>4</Column>
                </Position>
                <TileType>BUILDING</TileType>
                <BuildingType>HIRING_CENTER</BuildingType>
                <HazardType>null</HazardType>
                <Objective>
                    <ObjectiveStatus>HAS_OBJECTIVE</ObjectiveStatus>
                    <ObjectiveAction>HIRE_BUILDER</ObjectiveAction>
                    <ObjectiveQuantity>3</ObjectiveQuantity>
                </Objective>
            </Tile>
            <Tile>
                <Position>
                    <Row>1</Row>
                    <Column>0</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>1</Row>
                    <Column>1</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>1</Row>
                    <Column>2</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>1</Row>
                    <Column>3</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>1</Row>
                    <Column>4</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>2</Row>
                    <Column>0</Column>
                </Position>
                <TileType>HAZARD</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>BANDITS</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>2</Row>
                    <Column>1</Column>
                </Position>
                <TileType>HAZARD</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>ROCKSLIDE</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>2</Row>
                    <Column>2</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>2</Row>
                    <Column>3</Column>
                </Position>
                <TileType>HAZARD</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>FLOOD</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>2</Row>
                    <Column>4</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>3</Row>
                    <Column>0</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>3</Row>
                    <Column>1</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>3</Row>
                    <Column>2</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>3</Row>
                    <Column>3</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>3</Row>
                    <Column>4</Column>
                </Position>
                <TileType>BUILDING</TileType>
                <BuildingType>TRAIN_STATION</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>4</Row>
                    <Column>0</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>4</Row>
                    <Column>1</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>4</Row>
                    <Column>2</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>4</Row>
                    <Column>3</Column>
                </Position>
                <TileType>EMPTY</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
            <Tile>
                <Position>
                    <Row>4</Row>
                    <Column>4</Column>
                </Position>
                <TileType>START</TileType>
                <BuildingType>null</BuildingType>
                <HazardType>null</HazardType>
            </Tile>
        </Board>
        <Time>2025-01-16T20:50:03.920128</Time>
    </GameMove>
    <GameMove>
        <PlayerState>
            <Points>0</Points>
            <Money>75</Money>
            <TrainProgress>1.0</TrainProgress>
            <CowDeck>
                <CowType name="HOLSTEIN">
